### ISSUE TITLE
demo pages

### ISSUE THREAD

**Issue by Frolikow** [dindeni/ui#1]
На странице набора элементов, нужно структурировать в соответствии с макетом. На макете есть несколько блоков с элементами, можно сделать эти блоки на одной странице друг под другом. Сейчас все выглядит просто налепленным одно на другое.
![image](https://user-images.githubusercontent.com/25764783/64450781-0a5a9780-d10d-11e9-9cd1-1f4b5a387b19.png)

___
на некоторых страницах отеля, фоновая картинка не на всю ширину окна. Нужно исправить в соответствии с макетами

**Comment by Frolikow** [comment]
расхождения с макетом:
1) отображается только число, при выборе гостей. и кнопка очистить другого цвета
![image](https://user-images.githubusercontent.com/25764783/65028710-a9319000-d966-11e9-85a7-a883b49ca7da.png)
2) разные шрифты над инпутом(font-weigth по крайней мере). Внутри инпута цвет шрифта другой. radioButton имеет дефолтное значение
![image](https://user-images.githubusercontent.com/25764783/65029054-44c30080-d967-11e9-91de-d8c96911eee0.png)
3) В календаре расхождения с макетом при выборе даты. На днях не отображается выбранные даты. + при нажатии "выезд" который справа на скрине - календарь открывается слева
![image](https://user-images.githubusercontent.com/25764783/65029415-e8141580-d967-11e9-960b-3924e0b27284.png)
4) нету выделения жирным, ни по дефолту, ни при ховере, никак. Возле Services не хватает элемента.  Cosmin Negoita - надпись упала вниз
![image](https://user-images.githubusercontent.com/25764783/65029711-738da680-d968-11e9-8eb2-a36e565cc757.png)
5) при уменьшении ширины окна - иконка плывёт
![image](https://user-images.githubusercontent.com/25764783/65030003-f6aefc80-d968-11e9-889d-07f7dc7e7ec6.png)
6) странное выравнивание кнопок
![image](https://user-images.githubusercontent.com/25764783/65030109-2eb63f80-d969-11e9-8b0e-69f032f429be.png)
7) у слайдера есть дефолтное значение
![image](https://user-images.githubusercontent.com/25764783/65030426-c2880b80-d969-11e9-981b-5633ab17e53f.png)
8) зачем-то круг посередине, которого нету в макете
![image](https://user-images.githubusercontent.com/25764783/65030527-e8adab80-d969-11e9-9c15-9ad6170a4988.png)
9) со всех элементов на которых остались аутлайны - надо убрать.Особенно в подобных местах надо обратить внимание 
![image](https://user-images.githubusercontent.com/25764783/65030736-3de9bd00-d96a-11e9-9aea-be5302601f47.png)
10) при клике "влево" происходит нечто странное(см.скрин). при клике "вправо" происходит ничего)
![image](https://user-images.githubusercontent.com/25764783/65030945-9ae57300-d96a-11e9-9455-2a5e58b38b0c.png)

Пока что все)

**Comment by dindeni** [comment]
2. Не очень понятно про заголовки над input. Несколько раз проверял, там у меня  Montserrat, font-weight: bold. Или нужно подгружать отдельный шрифт  Montserrat-bold ?

**Comment by Frolikow** [comment]
1) Список гостей перестал работать ( не открывается выпадающий список)
2) по заголовкам: в макете шрифт стоит `Montserrat`, а у тебя `Montserrat-regular`. Если использовать. Попробовал подключить другие шрифты от Montserrat, результат тот же, так что считаем выполненным)
3) календари вообще не открываются, ни один. Что-то лишнее подкрутил похоже)
4) ок
5) ок
6) ок
7) слайдер куда-то пропал 
![image](https://user-images.githubusercontent.com/25764783/66545981-17343600-eb66-11e9-95dd-176b606f30cb.png)
8) теперь справа фишка бессмысленная получилась
![image](https://user-images.githubusercontent.com/25764783/66546022-35019b00-eb66-11e9-98c5-0227da5a1e6c.png)
9) ок
10) стрелки не работают теперь. 

11) где-то что-то починил, и сломались все выпадающие списки)

**Comment by dindeni** [comment]
Возможно произошла путаница в комитах, последний(dbb86df5) должен точно работать

**Comment by dindeni** [comment]
Возможно произошла путаница в комитах, последний(bd0d0579) должен точно работать

**Comment by Frolikow** [comment]
новые выявленные проблемы:
1) там где элементы отдельно лежат, не работают выпадающие списки, и я могу в них записать вообще хоть что. (видео в 1.zip)
[1.zip](https://github.com/dindeni/ui/files/3746362/1.zip)
___
2) в блоке поиска номера "под пожелания", странное поведение. выпадающий календарь "прыгает" странно. И при открытом списке гостей, календарь уходит под него(тут скорее проблема списка гостей - лучше добавить анфокус для него). (видео в 2.zip)
[2.zip](https://github.com/dindeni/ui/files/3746365/2.zip)
___
3) при выборе дат - закрашивание накладывается слоями - выглядит как баг
![image](https://user-images.githubusercontent.com/25764783/67139449-83a3e900-f27a-11e9-97a2-f92026d5aaf9.png)
___
4) И по датам еще нужно продумать ограничение для выбора дат( 1-ая не больше 2-ой, а 2-ая не больше 1-ой)
![image](https://user-images.githubusercontent.com/25764783/67139540-91a63980-f27b-11e9-819e-912f2f87e92e.png)

**Comment by Frolikow** [comment]
1.ok
2.ok
3. в календаре иногда ломается верстка. 
![image](https://user-images.githubusercontent.com/25764783/67637957-6b833800-f912-11e9-9302-eb919d982b4e.png)
___
![image](https://user-images.githubusercontent.com/25764783/67637975-8c4b8d80-f912-11e9-9301-276806af5d97.png)
здесь один выпадающий элемент уходит под нижний блок(при клике по блоку). и оба закрываются только при клике `применить`. Я бы сделал скрытие списка при анфокусе тоже. Это как-то интуитивно ожидаемо, тем более что на календарях это реализовано и крайне странно наблюдать разное поведение у выпадающих элементов.

**Comment by Frolikow** [comment]
в целом все ок по юи-киту, только поправь еще выравнивание текста у чекбоксов и радио. По макету текст относительно инпута отцентрован
Макет: 
![image](https://user-images.githubusercontent.com/25764783/68087068-c4a81a00-fe84-11e9-9336-21910915de9d.png)
у тебя: 
![image](https://user-images.githubusercontent.com/25764783/68087076-da1d4400-fe84-11e9-816a-ad19989f63e2.png)

**Comment by Frolikow** [comment]
Не понял, почему не все исправил, проверь все элементы внимательно. Примеры: 
![image](https://user-images.githubusercontent.com/25764783/68541208-31646c80-03cf-11ea-8b74-d7b4a816c193.png)
![image](https://user-images.githubusercontent.com/25764783/68541321-9c627300-03d0-11ea-80c8-9f5d8b4a0b33.png)
![image](https://user-images.githubusercontent.com/25764783/68541329-ab492580-03d0-11ea-99b1-d21463f135fd.png)
![image](https://user-images.githubusercontent.com/25764783/68541369-198de800-03d1-11ea-856f-c914620b5dd5.png)
![image](https://user-images.githubusercontent.com/25764783/68541384-43470f00-03d1-11ea-9b01-74d5e52f1dc9.png)
