### ISSUE TITLE
Атрибуты миксинов

### ISSUE THREAD

**Issue by Frolikow** [dindeni/ui#11]
Атрибуты миксинов лучше передавать объектом. 
Самая большая польза от этого - это, неважность порядка переданных атрибутов. 

Плюс еще большая проблема в том что у тебя атрибутом передается класс модификатора. Это тоже очень плохая практика и выглядит очень костыльно. Здесь могу предложить как вариант передавать какую-то переменную modifer, которая будет в себе хранить сам модификатор. А внутри миксина ты его уже используешь в нужном месте, например с помощью шаблонных строк что то типа `button button_${modifer}`.

**Comment by dindeni** [comment]
Для миксинов с одним атрибутом не стал создавать объект, думаю есть смысл только для множественных атрибутов.

**Comment by Frolikow** [comment]
А почему в подобных местах не передать просто объект?Все равно ведь внутри деструктуризацию делаешь.  И объем кода сократиться и `footerdata` не будет дублироваться
![image](https://user-images.githubusercontent.com/25764783/67140297-64f62000-f283-11e9-9af7-9f8a63a6e786.png)
 и внутри миксина названия свойств объекта будут без`footerWidget...`
![image](https://user-images.githubusercontent.com/25764783/67140356-e77edf80-f283-11e9-965a-284a3c0d6911.png)

**Comment by Frolikow** [comment]
почему `uiNavBar` не передать объектом? в нем же 2 поля, и ты оба передаешь
![image](https://user-images.githubusercontent.com/25764783/67638529-db47f180-f917-11e9-822d-0b7817436f0a.png)
и тут :
![image](https://user-images.githubusercontent.com/25764783/67638537-06324580-f918-11e9-8d7a-c029620e83bd.png)
![image](https://user-images.githubusercontent.com/25764783/67638542-18ac7f00-f918-11e9-9d71-d4fb0f8f7e0b.png)
![image](https://user-images.githubusercontent.com/25764783/67638544-1ea26000-f918-11e9-80e4-49330d3088d6.png)
___
внутри `each..in `можно деструктуризацию для `value` сделать и не писать в каждом атрибуте одно и тоже слово
![image](https://user-images.githubusercontent.com/25764783/67638557-56110c80-f918-11e9-994a-2823db0aff75.png)
___
`label` деструктурировал с заглавной буквы и поэтому подписи везде отвалились
![image](https://user-images.githubusercontent.com/25764783/67638645-74c3d300-f919-11e9-9e25-8e497dc9c594.png)
![image](https://user-images.githubusercontent.com/25764783/67638647-82795880-f919-11e9-8cb3-0cf4c834f6b4.png)
___
можно сразу передать переменную, и не переприсваивать ее в одноименное поле объекта 
![image](https://user-images.githubusercontent.com/25764783/67638775-2dd6dd00-f91b-11e9-8d88-24af9f50891f.png)
___
на счет `each..in` выше писал)
![image](https://user-images.githubusercontent.com/25764783/67638852-e13fd180-f91b-11e9-90b5-a9315b752662.png)
___
есть ли смысл здесь опять переписывать значения? мб можно `arrTotalDesc` вначале файла назвать `totalValue`? то же касается и `totalPrice: arrTotalPrice`
![image](https://user-images.githubusercontent.com/25764783/67638870-06ccdb00-f91c-11e9-8432-1028fd72eb06.png)
___
тоже лучше деструктурировать 
![image](https://user-images.githubusercontent.com/25764783/67639173-3df0bb80-f91f-11e9-8ecd-c51bc029570a.png)
___
_замечание не по атрибутам_. Тут у тебя выделенные строки повторяются трижды, в каждом `if`е. Может их можно вынести из условий?
![image](https://user-images.githubusercontent.com/25764783/67639230-020a2600-f920-11e9-98a7-518c12514992.png)
___
