### ISSUE TITLE
Структура папок, миксины, БЭМ, общие замечания - всего понемногу.

### ISSUE THREAD

**Issue by Sergio-Ka** [dindeni/ui#13]
Каждый пункт исправлять отдельным коммитом. Коммитам давать осмысленные названия. Ссылаться на issue через знак #.

1. Сейчас в pugTemplates в файлах там где используется миксин для навигации написана конструкция вида Object.assign(navigationValues, {...}). Эта конструкция во-первых плохо воспринимается и не очевидна, во-вторых мутируется целевой объект. А мы стараемся избегать мутаций и как правило это почти всегда возможно. Надо переписать с использованием spread оператора (троеточие) - и кроме того это общекомандный кодстайл, хотя явно это не указано. Никто не пишет через Object.assign у нас добавление свойств объекта.
2. Папка common лежит в блоках, хотя ее содержание к блоку не относится. Надо поднять на уровень выше (рядом с favicons) и положить в какую-нибудь папку scss или style. Так же стоит поступить с папками mixins и variables. И даже их содержимое возможно стоит положить в ту же папку scss или style.
3. В README.md добавить явно команду на клонирование репозитория типа git clone "ссыль-на-твою-репо".
4. Конструкции экранированные знаком тире в pug это фактически js и стало быть для него так же распространяются все правила по кодстайлу для js. И когда я не вижу точки с запятой в конце строк выражений это очень бросается в глаза. Здесь цель - писать всегда в одном общекомандном стиле в независимости от типа файла. В противном случае код выглядит неряшливо, плохо воспринимается, затрудняет совместную разработку. И нужно привыкать писать сразу красиво. Поэтому это замечание не то чтобы придраться - а чтобы выработать у тебя сразу устойчивые привычки и стиль кода.
5. form-element - много сущностей в одном месте. Во-первых у тебя примерно повторяющаяся структура - либо div либо label а внутри input. Меняются только классы и типы - зачем тут дублировать постоянно структуру? Делаешь в if...else или в switch выбор класса, типа и еще чего там надо в переменную и просто в конце присваиваешь ее классу описанной один раз структуре, а не так как сейчас, структура генерится каждый раз в каждой ветке ветвления. Во вторых вообще спорно возможно такое решение. У тебя миксин выплевывает разную верстку в зависимости от условий и если тебе где-то надо использовать один маленький инпут  - ты дергаешь весь громадный миксин. Решение как минимум спорное и едва ли удобное. Ибо это компонент-монстр. Возможно стоит разбить на несколько компонент этот большой миксин. Но тут не точно, надо подумать и возможно попробовать реализацию по первому способу.
6. main-filter - странный блок без структуры, только стили (где компонентность? где выполнение требования что миксины должны быть выделены в папки?) и все остальные с префиксом main и ui. Здесь даже в файле filter.pug видно что болтается блок main-filter без выполнения этих требований. Это такой же БЭМ блок (компонент), а стало быть должен оформляться виде миксина в отдельной папке в которой должны лежать все его реализации (как раз все эти стилевые файлы например, что болтаются в папках с префиксом main и ui). Ну и кроме того, то как сделано сейчас, а именно .main-filter__header идет в начале, а потом идет .main-filter. Элемнт блока должен быть всегда в блоке, а стало быть тут предположительно надо сделать div обертку с классом .main-filter у которого будет header с классом .main-filter__header и то что сейчас зовется .main-filter будет зваться например как-нибудь .main-filter__content. Здесь main-filter рассмотрен для примера, эти замечания касаются всех страниц, что сейчас оформлены схожим образом.
7. Зачем миксин scss под названием hideClass если он нигде не используется?
8. Сборка проекта с ошибкой, не подключается стилевой файл, потому что путь в конфиге webpack'а указан как './build/style.css',  а по факту от index.html будет './style.css'.

**Comment by dindeni** [comment]
1. Переписал через деструктуризацию, так как spread оператор объектов в pug не работает, только массивы получаются.

**Comment by Sergio-Ka** [comment]
Хорошо!
