### ISSUE TITLE
Файловая структура

### ISSUE THREAD

**Issue by imin314** [dindeni/ui#16]
Для изображений в блоках лучше создавать подпапки:
![img](https://user-images.githubusercontent.com/40715953/76519951-7fc86b80-6494-11ea-8b94-91db2309a83c.png)

Тогда, если в блоке потребуется много картинок, структура папки не будет перегруженной.

**Comment by imin314** [comment]
1) В блоке лучше хранить только картинки, которые используются только в нем. Если это общие на сайт иконки, надо их поместить в общую папку с изображениями:
![Выделение_115](https://user-images.githubusercontent.com/40715953/79064456-6b65d180-7cd3-11ea-8790-2ef1ac3e21c5.png)
![Выделение_116](https://user-images.githubusercontent.com/40715953/79064457-6dc82b80-7cd3-11ea-81be-cef1a5afdf6c.png)

2) Круглая форма аватарки, граница и тень должны быть сделаны через css:
![Выделение_118](https://user-images.githubusercontent.com/40715953/79064518-ad8f1300-7cd3-11ea-9254-761e4489aa5f.png)

**Comment by imin314** [comment]
А картинки для этого блока разве еще где-то используются?
![Выделение_046](https://user-images.githubusercontent.com/40715953/79563901-d8b0a280-80d7-11ea-90fb-056d92f5cf28.png)

**Comment by dindeni** [comment]
Только в этом, но подключается в двух местах и там разные изображения(какие-то повторяются), пути просто передаются через параметр. Если вынести их в блоки где они подключаются, получится повторение, поэтому вынес в общую папку.
