### ISSUE TITLE
Блок button

### ISSUE THREAD

**Issue by imin314** [dindeni/ui#19]
Код блока кажется перегруженным. По идее, когда у тебя встречается много однотипных else if, можно их заменить оператором switch-case. Но в данном случае, похоже, что проблема кроется в непродуманности блока.

Во-первых, названия элементов full, transparent, bordering не отражают сути содержимого. Название элемента должно отвечать на вопрос "что?", а не "какой?". Поскольку у тебя от типа кнопки в основном зависят классы, которые ты используешь для элементов, а структура почти не изменяется, есть смысл сделать один общий элемент, на который ты просто будешь навешивать модификаторы.

Тут еще вопрос, зачем нужна обертка в виде div.button? Я заметила, что в стилях классов для блока ты определяешь внешнюю геометрию:
![Снимок экрана-20200313164624-247x101](https://user-images.githubusercontent.com/40715953/76609600-38041b80-654a-11ea-8639-84c6efb718ed.png)

Так делать не нужно. Все внешние отступы задаются не в блоке, а с помощью элемента-обертки в том месте, где ты будешь использовать свой блок. Попробуй в общем избавиться от div.button и всю внешнюю геометрию определять вне блока.

Во-вторых, кажется, что у тебя есть лишние типы кнопок. Например, 
кнопки с типом full-link и bordering-link. Я так поняла, что full и bordering отвечают за внешний вид кнопки. а link - за наличие ссылки. Можно же не плодить лишние классы, а создать модификатор вроде type_link и навешивать его дополнительно к full и bordering.

В-третьих, обрати внимание на названия модификаторов типа "ключ-значение". button_gray - некорректное название. Должен быть ключ.

По этому блоку еще будут замечания, скорее всего. Но пока структуру блока не поправишь, смысла проверять нет.

**Comment by imin314** [comment]
И проверь в остальных блоках тоже, пожалуйста:
1) Названия модификаторов "ключ-значение".
2) Не задаешь ли ты внешние отступы в главном классе блока.
3) Не используешь ли ты в верхнем уровне блока _div-обертки_, чтобы задавать положение блока (которое по идее нужно определять вне блока).

Если есть вопросы, не стесняйся спрашивать.

**Comment by dindeni** [comment]
Блок полностью переписал. Обертка нужна для градиентной рамки. Модификаторы поправил, для которых нужно значение, остальные как булевые.

**Comment by imin314** [comment]
Только сейчас заметила, что стили блока button переехали в общие миксины, из-за чего нарушается БЭМ.
По идее общие стили должны быть установлены самому блоку (напрямую, не через миксин). Модификаторы только переопределяют, дополняют какие-то конкретные свойства (цвет, псевдо-элементы и т. д.). А сейчас получается, что стили каждого модификатора целиком "создают" кнопку: 
![Выделение_147](https://user-images.githubusercontent.com/40715953/80286090-9d574900-8753-11ea-8b0b-22e424d3b100.png)
