### ISSUE TITLE
Отзывчивость

### ISSUE THREAD

**Issue by imin314** [dindeni/ui#38]
1) При уменьшении ширины окна блок для подбора номера начинает перекрывать все остальные блоки и выходить за границы баннера:
![Выделение_108](https://user-images.githubusercontent.com/40715953/79063058-89c6cf80-7cc9-11ea-8716-b910e066dead.png)

2) Под футером виден datepicker:
![Выделение_109](https://user-images.githubusercontent.com/40715953/79063099-d8746980-7cc9-11ea-9be4-1ec6dadd8dcf.png)

3) Это меню по умолчанию должно быть скрыто:
![Выделение_110](https://user-images.githubusercontent.com/40715953/79063154-09ed3500-7cca-11ea-9c3f-a648c3f6044f.png)

**Comment by imin314** [comment]
На странице filters при увеличении ширины экрана всё содержимое должно выравниваться по центру, а оно остается слева.
![Выделение_132](https://user-images.githubusercontent.com/40715953/79068248-b68ddd80-7cef-11ea-865a-01bada46fa61.png)

**Comment by dindeni** [comment]
> На странице filters при увеличении ширины экрана всё содержимое должно выравниваться по центру, а оно остается слева.
> ![Выделение_132](https://user-images.githubusercontent.com/40715953/79068248-b68ddd80-7cef-11ea-865a-01bada46fa61.png)

Теперь центруется, кроме максимального разрешения, там оставил как в макете, чтобы соответствовал.
