### ISSUE TITLE
Несоответствия макету

### ISSUE THREAD

**Issue by imin314** [dindeni/ui#40]
1) Страница ui-page.html не соответствует макету. Вверху каждой группы с элементами ui есть лого и серый фон:
![Выделение_119](https://user-images.githubusercontent.com/40715953/79064747-cac4e100-7cd5-11ea-8b0a-0a6db96e88a0.png)

2) Не нашла страницы _Colors & Type_:
![Выделение_120](https://user-images.githubusercontent.com/40715953/79064818-4161de80-7cd6-11ea-897c-4b4caa2b12b1.png)

**Comment by imin314** [comment]
2. Страница **UI-kit**:
2.1. Для всех инпутов отсутствуют лэйблы: 
![Выделение_130](https://user-images.githubusercontent.com/40715953/80285373-a691e700-874e-11ea-8cd8-2545dd8d196e.png)

2.2. Выравнивание содержимого инпутов нужно делать не с помощью подстраивания line-height, а с помощью padding (сейчас вертикально не выровнено по центру):
![Выделение_135](https://user-images.githubusercontent.com/40715953/80285479-857dc600-874f-11ea-8d06-de482e3ba90c.png)

2.3. Masked text-field не работает:
![Выделение_136](https://user-images.githubusercontent.com/40715953/80285517-c5dd4400-874f-11ea-8947-010e994f75a7.png)

2.4. Subscription text-field (цвет и написание плейсхолдера):
![Выделение_140](https://user-images.githubusercontent.com/40715953/80285729-10ab8b80-8751-11ea-9e8f-c3379556c214.png)

2.5. В радио-кнопках другой текст:
![Выделение_142](https://user-images.githubusercontent.com/40715953/80285799-8b74a680-8751-11ea-9dde-a03289e45c74.png)
![Выделение_143](https://user-images.githubusercontent.com/40715953/80285814-acd59280-8751-11ea-9c7d-ab1fabad8872.png)

2.6. В rich checkbox buttons высота строки для описания слишком маленькая. На скрине разница между PixelPerfect и сайтом кажется незначительной, но на самом деле визуально бросается в глаза:
![Выделение_149](https://user-images.githubusercontent.com/40715953/80286245-69c8ee80-8754-11ea-91ac-3988d5e1a081.png)

2.7. Нет горизонтальных линий:
![Выделение_150](https://user-images.githubusercontent.com/40715953/80286296-be6c6980-8754-11ea-8150-12f19d87dea6.png)

2.8. Для слайдера пропал лэйбл, диапазон цены справа уехал за пределы слайдера.
![Выделение_128](https://user-images.githubusercontent.com/40715953/80285196-6bdb7f00-874d-11ea-897c-fff101ebf106.png)

2.9. В макете другой размер шрифта:
![Выделение_152](https://user-images.githubusercontent.com/40715953/80286319-f1166200-8754-11ea-90f0-229a20ee8ba8.png)

**Comment by imin314** [comment]
На этой странице еще остались недоработки:
1) В dropdown:
* неправильные склонения (гостей, младенцев),
* левые кнопки прыгают в зависимости от количества гостей
* названия категорий должны быть заглавными буквами и другим цветом
![Выделение_323](https://user-images.githubusercontent.com/40715953/82047711-7bf7d600-96dd-11ea-8035-d170be72380d.png)

* Если дропдаун закрыть и сразу закрыть, то текст будет "0 гостей" вместо плейсхолдера "Сколько гостей".
![Выделение_321](https://user-images.githubusercontent.com/40715953/82047751-92059680-96dd-11ea-9c26-b0c2fcbd7796.png)
* Плейсхолдер должен быть светло-серым.

2) Должны быть DATE DROPDOWN и FILTER DATE DROPDOWN:
![Выделение_327](https://user-images.githubusercontent.com/40715953/82048192-61722c80-96de-11ea-8934-46b906a7d1b7.png)

3) В masked text field при фокусе меняется плейсхолдер:
![Выделение_322](https://user-images.githubusercontent.com/40715953/82048277-9a120600-96de-11ea-88e1-4bfbbce7000b.png)

4) Нет дропдауна для выбора параметров номера:
![Выделение_323](https://user-images.githubusercontent.com/40715953/82048398-cded2b80-96de-11ea-8b6c-0c24a95ebc9d.png)

**Comment by dindeni** [comment]
Насчет плейсхолдера в инпуте подсчета гостей не совсем понятно:
Вот так на макете:
![2020-05-19_23-01](https://user-images.githubusercontent.com/25766511/82367758-5e9c7200-9a25-11ea-9fb6-d6985c82af49.png)
У меня в devtools:
![2020-05-19_23-02](https://user-images.githubusercontent.com/25766511/82367990-b33fed00-9a25-11ea-9c87-012206f64971.png)
Как я понимаю - один и тот же цвет.

**Comment by imin314** [comment]
> Насчет плейсхолдера в инпуте подсчета гостей не совсем понятно:
> Вот так на макете:
> ![2020-05-19_23-01](https://user-images.githubusercontent.com/25766511/82367758-5e9c7200-9a25-11ea-9fb6-d6985c82af49.png)
> У меня в devtools:
> ![2020-05-19_23-02](https://user-images.githubusercontent.com/25766511/82367990-b33fed00-9a25-11ea-9c87-012206f64971.png)
> Как я понимаю - один и тот же цвет.

Да, тут я ошиблась, извиняюсь. Цвет сейчас правильный установлен.
