### ISSUE TITLE
bundle/build

### ISSUE THREAD

**Issue by Frolikow** [dindeni/ui#5]
Не совсем понятен смысл нахождения в проекте html файлов для страниц. Если это файлы твоего бандла, то они как и bundle.js и css должны собираться вебпаком в отдельную папку, например `bundle` / `build`

**Comment by Frolikow** [comment]
Не много неправильно получилось. Сейчас у тебя сборка твоя лежит в папке src, это как минимум не логично. В папке src лежит то из чего собирается проект, но точно не уже собранный проект)

**Comment by Frolikow** [comment]
не увидел сразу
бандл в src все еще лежит зачем-то 
![image](https://user-images.githubusercontent.com/25764783/66550802-5bc4cf00-eb70-11e9-85b1-9b5de5e13f40.png)

**Comment by dindeni** [comment]
Откатился на последние исправления(0f206c9f), там исправлен конфиг. Возможно эти файлы остались с прошлых сборок, сейчас все собирается в build.
