### ISSUE TITLE
Адаптивность

### ISSUE THREAD

**Issue by Fr0stmourne** [dindeni/ui#64]
Лучше сделать одинаковые отступы по странице, а то неаккуратно смотрится: в отзывах отступа нет вообще, в сведениях есть небольшой, в хедере еще больше, в футере снова нет

![image](https://user-images.githubusercontent.com/46089168/105463449-1f53ae80-5ca1-11eb-907a-6e89afb42115.png)

**Comment by Fr0stmourne** [comment]
Футер в мобильной версии нужно поменять на вот этот, он вроде специально для адаптивности в макете дан
![image](https://user-images.githubusercontent.com/46089168/107039261-b145d600-67ce-11eb-9367-114b2cb77215.png)

**Comment by Fr0stmourne** [comment]
> Лучше сделать одинаковые отступы по странице, а то неаккуратно смотрится: в отзывах отступа нет вообще, в сведениях есть небольшой, в хедере еще больше, в футере снова нет
> 
> ![image](https://user-images.githubusercontent.com/46089168/105463449-1f53ae80-5ca1-11eb-907a-6e89afb42115.png)

Эту проблему нужно по всем страницам посмотреть, к примеру, на странице с фильтрами вот так. В целом, идея такая, что между всеми страницами должна быть похожая сетка документа с отступами
![image](https://user-images.githubusercontent.com/46089168/107041269-5c578f00-67d1-11eb-9868-2e71085b660c.png)

**Comment by Fr0stmourne** [comment]
На странице номера горизонтальный скролл на 320px появился:

![image](https://user-images.githubusercontent.com/46089168/109116270-4f371b80-7751-11eb-903d-0a924e1aa231.png)

**Comment by Fr0stmourne** [comment]
Футер так и остался старый

**Comment by dindeni** [comment]
Наверно не так понял, теперь скрыл списки в футере
