### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Fr0stmourne** [dindeni/ui#66]
- Лучше медиа-выражения вкладывать в селекторы, то есть вместо

![image](https://user-images.githubusercontent.com/46089168/107042899-4ea30900-67d3-11eb-8e34-45989eb707e0.png)

переписать так:
![image](https://user-images.githubusercontent.com/46089168/107043249-cb35e780-67d3-11eb-96e9-a108498dcaae.png)

- Нужно почистить закомменченный код
- В списках лучше с помощью селектора `:last-child` обнулять ненужный отступ для последнего элемента, чтобы это потом не мешалось нигде
![image](https://user-images.githubusercontent.com/46089168/107043682-64fd9480-67d4-11eb-8a7b-ac53bf59febb.png)

**Comment by Fr0stmourne** [comment]
А чем обусловлено использование `margin` и `padding` в %? На мой взгляд, не всегда очевидно, сколько там будет отступ в итоге, это сложно поддерживать, лучше в абсолютных величинах их задавать

**Comment by dindeni** [comment]
Чтобы меньше media писать, поправил
