### ISSUE TITLE
Мелочи

### ISSUE THREAD

**Issue by Fr0stmourne** [dindeni/ui#67]
Тут вроде можно `toggle` использовать

![image](https://user-images.githubusercontent.com/46089168/107043817-8e1e2500-67d4-11eb-9657-763d6486c667.png)

**Comment by dindeni** [comment]
Через checkbox упростил

**Comment by Fr0stmourne** [comment]
Вообще вариант с переключением классов предпочтительнее, да и пишется тоже в 1 строчку
