### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Frolikow** [dindeni/ui#7]
+ Мы используем БЭМ вида блок__элемент_модификатор. Надо привезти весь проект к подобному виду. 
+ Примеси на тегах использовать запрещено.
+ классы должны отображать смысл блока или элемента. В данном случае какой смысл скрыт в классе?(ответ не обязателен;))
![image](https://user-images.githubusercontent.com/25764783/64452820-590a3080-d111-11e9-8cca-02c7a5bcb201.png)
+ в каждом миксине должен лежать только 1 блок. Имя миксина, блока и файла должны совпадать, включая регистр. В директории с блоком должны лежать файлы только для этого конкретного блока, будь то стили или js. 
+ При именовании классов не использовать нотацию camelCase. Мы используем kebab-case. Можешь сразу к ней привыкать.
+ По БЭМу, использование идентификаторов запрещено
+

**Comment by dindeni** [comment]
Оставил id для checkbox, radio, так как они нужны для их работы без js.

**Comment by Frolikow** [comment]
1) Ок
2) _примеси - вроде ок, не увидел больше_
3) Повторюсь, классы должны максимально отображать смысл, называть классы по тегам это не лучший вариант. например 
```js
span.checkbox__span #{value.description}
```
ладно блок чекбокс - ок. но здесь у тебя даже подписано что в нем лежит( description).
4) это выполнено не полностью. Проверь еще раз проект. Директория, файл внутри директории, миксин в файле и блок который из миксина должны иметь одно имя. 

5) опять же надо проверить по всему проекту
6) _хорошо_

**Comment by Frolikow** [comment]
Стили.
В директории с блоком, могут лежать стили только для этого блока. Стили другого блока, должны быть рядом со свсоим блоком, ни каких переопределений не должно быть. Для этого есть модификаторы

**Comment by Frolikow** [comment]
очень странные классы на элементе
![image](https://user-images.githubusercontent.com/25764783/67638076-8bffc200-f913-11e9-98b2-9e125f52cab1.png)
___
зачем два раза класс задаешь
![image](https://user-images.githubusercontent.com/25764783/67638663-af2d7000-f919-11e9-8485-21f9ddfd2937.png)
![image](https://user-images.githubusercontent.com/25764783/67638667-b81e4180-f919-11e9-9e69-e13aa8f8fa76.png)
___
и здесь двойной класс
![image](https://user-images.githubusercontent.com/25764783/67639008-6c6d9700-f91d-11e9-9f8a-8ffb848c82e2.png)
